# * Tensorboard Visualization Parameters
# should enable Tensorboard first
board_vis_item:
  desc: Visualization of dataloader item list, -1 means all
  value: -1
board_vis_input_enable:
  desc: Visualization of dataloader input and ground truth 
  value: false
board_vis_mid_enable:
  desc: Visualization of mid result (video sequence output)
  value: false
board_vis_res_enable:
  desc: Visualization of finally result (merge all video sequences output)
  value: false
board_vis_res_size:
  desc: Visualization of finally result size (Width, Height)
  value: 
    - 960
    - 540
board_vis_res_interval:
  desc: Visualization of finally result interval (start, end, step) on board
  value: 
    - 1
    - 100
    - 1
board_vis_res_events:
  desc: Visualization of finally result with mot events
  value: true
board_vis_res_save:
  value: false
# Ablation Parameters
abla_vis_decattn_enable:
  desc: Visualization of decoder cross attention
  value: false
abla_vis_objquery_enable:
  desc: Visualization of object queries
  value: false
abla_vis_traquery_enable:
  desc: Visualization of track queries
  value: false
abla_vis_obj_num:
  desc: The number of objects to visualize the attention ablation
  value: 1
abla_vis_que_num:
  desc: The number of queries to visualize the queries ablation
  value: 3
abla_vis_frame_step:
  desc: The frame step to visualize the ablation
  value: 2