__base__: 
  desc: the base config yaml
  value: __base__/mmotr.yaml

# * Train & Eval
resume:
  desc: the model resume checkpoint
  value: ''
epochs:
  value: 100

# * Transformer
num_queries:
  desc: Number of query slots
  value: 50

# * Dataset Parameters
dataset_name:
  value: ua
dataset_path:
  value: data/UA_DETRAC
num_workers:
  desc: number of workers to load data
  value: 4
batch_size:
  value: 2
eval_batch_size:
  value: 2

# * Tensorboard
board_enable:
  value: true
board_dir:
  value: 'runs'
board_freq:
  value: 10