# The small model setting
__base__: 
  desc: the base config yaml
  value: 
    - __base__/deformable_mmotr.yaml
    - __base__/ablation.yaml

# * Train & Eval
epochs:
  value: 50
eval_period:
  desc: eval period of epochs
  value: 50

# * Transformer
num_encoder_layers:
  desc: Number of encoding layers in the transformer
  value: 3
num_decoder_layers:
  desc: Number of decoding layers in the transformer
  value: 3
dim_feedforward:
  desc: Intermediate size of the feedforward layers in the transformer blocks
  value: 1024
start_level:
  desc: The start level of backbone features to embed
  value: 1
extra_levels:
  desc: Extra levels need to embed conved from last backbone feature
  value: 1
num_queries:
  desc: Number of query slots
  value: 100

# * Dataset Parameters
dataset_name:
  value: ua
dataset_path:
  value: data/UA_DETRAC
train_max_size:
  desc: max size (448, 796) of random resize of input frames
  value: 796
eval_size_list:
  desc: size set of random resize of input frames
  value:
    - 448
output_dir:
  desc: path where to save, keep empty for an auto-generated date-time labeled folder
  value: output/demmotr_ua_s
num_workers:
  desc: number of workers to load data
  value: 4
batch_size:
  value: 2
eval_batch_size:
  value: 1

# * Tensorboard
board_enable:
  value: true
board_dir:
  value: runs/demmotr_ua_s
board_freq:
  value: 10

# * Tensorboard Ablation
# should enable Tensorboard first
board_vis_input_enable:
  desc: Visualization of dataloader input and ground truth 
  value: true
board_vis_mid_enable:
  desc: Visualization of mid result (video sequence output)
  value: true
board_vis_res_enable:
  desc: Visualization of finally result (merge all video sequences output)
  value: true
board_vis_res_save:
  value: true
board_vis_ablation_enable:
  desc: Visualization of attention ablation of DETR of DeformableDETR
  value: false
board_vis_item:
  desc: Visualization of dataloader item list, -1 means all
  value:
    - 0
    - 1
    - 46
    - 47